let userName = prompt('Write your name')
console.log(`Name: ${userName}`)
let abdulloh = prompt('Write your surname')
console.log(`Surname: ${abdulloh}`)
let Age = prompt('Write your Age')
console.log(`Age: ${Age}`)
let Aliaskarov = prompt('Write your favourite subject')
console.log(`Subject: ${Aliaskarov}`)
let manzil = prompt('Tumanni yozing')
console.log(`Tuman: ${manzil}`)
alert(`Добро пожаловать ${userName}`)